AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DesiredCapacityParam:
    Type: Number
    Default: 2
    Description: The desired capacity of the Auto Scaling Group.

Resources:
  WarmPoolPocSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Internal access only
      VpcId: !GetAtt WarmPoolPocVPC.VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/16
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 10.0.0.0/16
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 10.0.0.0/16

  WarmPoolPocLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: warm-pool-poc-launch-template
      LaunchTemplateData:
        ImageId: ami-08b5b3a93ed654d19 # Replace with your AMI ID
        InstanceType: t3.micro
        NetworkInterfaces:
          - AssociatePublicIpAddress: false
            DeviceIndex: 0
            Groups:
              - !Ref WarmPoolPocSecurityGroup
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: WarmPoolPocInstance

  WarmPoolPocAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: warm-pool-poc-asg
      MinSize: !Ref DesiredCapacityParam
      DesiredCapacity: !Ref DesiredCapacityParam
      MaxSize: !Ref DesiredCapacityParam
      VPCZoneIdentifier:
        - !Ref WarmPoolPocSubnet
      LaunchTemplate:
        LaunchTemplateId: !Ref WarmPoolPocLaunchTemplate
        Version: !GetAtt WarmPoolPocLaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: WarmPoolPocInstance
          PropagateAtLaunch: true

  WarmPoolPocWarmPool:
    Type: AWS::AutoScaling::WarmPool
    Properties:
      AutoScalingGroupName: !Ref WarmPoolPocAutoScalingGroup
      MinSize: 1
      PoolState: Stopped
      MaxGroupPreparedCapacity: 3

  WarmPoolPocVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: WarmPoolPocVPC

  WarmPoolPocSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref WarmPoolPocVPC
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: WarmPoolPocSubnet
